In [1]:
import random
# 随机数不一样
random.seed()
print('随机数1:',random.random())
random.seed()
print('随机数2:',random.random())


随机数1: 0.5298486666569063
随机数2: 0.9056758880035777


In [3]:
# 随机数一样
random.seed(6) # 参数随意，只是定个初始值
print('随机数3:',random.random())
random.seed(6)
print('随机数4:',random.random())

# 参数不一样的，随机数就不一样
random.seed(7)
print('随机数5:',random.random())

随机数3: 0.793340083761663
随机数4: 0.793340083761663
随机数5: 0.32383276483316237


- 随机数种子，相当于我给接下来需要生成的随机数一个初值，按照我给的这个初值，按固定顺序生成随机数。

（1）随机数种子相当于给我们一个初值，之后按照固定顺序生成随机数（也就是我们说的超级长的 list ）

（2）随机数种子对后面的结果一直有影响，在一个随机数种子后生成的随机数都受这个随机数种子的影响，即生成的随机数都是由这个随机数种子给的初值，按照固定顺序生成的。

（3）每次使用之前都需要调用一下：np.random.seed(0) 【 random.seed(0) 同理】

（4）np.random.seed(0)中参数0是随便取的，可以认为是初值的标志，每次按照这个标志都可以得到相同的初值

In [1]:
import numpy as np
np.random.seed(0)  # 先定义一个随机数种子
print(np.random.rand(5))  # "随机"生成5个数

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [2]:
import numpy as np
np.random.seed(0)  # 先定义一个随机数种子
print(np.random.rand(5))  # "随机"生成5个数
print(np.random.rand(5))  # 再"随机"生成5个数

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]


In [3]:
import numpy as np
np.random.seed(0)  # 先定义一个随机数种子
print(np.random.rand(5))  # "随机"生成5个数
print(np.random.rand(5))  # 再"随机"生成5个数

np.random.seed(0)
for i in range(7):
    print(np.random.random())  # "随机"生成7个数

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
0.5488135039273248
0.7151893663724195
0.6027633760716439
0.5448831829968969
0.4236547993389047
0.6458941130666561
0.4375872112626925


接下来我们的对比一下，最后输出的7个随机数的结果和我们之前分两次输出的随机数列表，

我们可以很清晰的看到：我们最后输出的7个随机数便是依次从我们之前的生成的10个随机数中取得的！ 

也就是说在代码中，我们看到 “ 随机 ” ，那就是说并不是真正随机（假随机）。

- 设置的seed()值仅一次有效

In [8]:
import numpy as np
# 参数问题：这个参数是随便取的，可以认为是初值的标志，每次按照这个标志都可以得到相同的初值
np.random.seed(0) 
print(np.random.rand(2, 3))

np.random.seed(1)
print(np.random.rand(2, 3))

np.random.seed(2)
print(np.random.rand(2, 3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]
[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]]


In [10]:
import numpy as np
####  使用前后都需要调用 np.random.seed(1)
np.random.seed(1)
L1 = np.random.randn(3, 3)
np.random.seed(1)
L2 = np.random.randn(3, 3)
print(L1)
print(L2)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842]]
